config/routes.rb
Rails.application.routes.draw do
  root 'mobiles#index'
  resources :mobiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mobile.rb
class Mobile < ApplicationRecord
  validates :price, :ram, :rom, :brand_name, presence: true
  after_destroy :set_count

  def set_count
    count = Mobile.all.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
  before_action :set_mobile, only: %i[ show edit update destroy ]
  after_action :count, only: %i[ new edit update destroy ]

  # GET /mobiles or /mobiles.json
  def index
    @mobiles = Mobile.all
  end

  # GET /mobiles/1 or /mobiles/1.json
  def show
    respond_to do |format|
      format.turbo_stream
    end
  end

  # GET /mobiles/new
  def new
    @mobile = Mobile.new
  end

  # GET /mobiles/1/edit
  def edit
  end

  # POST /mobiles or /mobiles.json
  def create
    @mobile = Mobile.new(mobile_params)

    respond_to do |format|
      if @mobile.save
        format.turbo_stream { render turbo_stream: turbo_stream.append("mobile_list", partial: 'mobiles/mobile', locals: {mobile: @mobile}) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("remote_modal", partial: 'mobiles/form_modal', locals: {mobile: @mobile, partial_file: 'form'}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mobiles/1 or /mobiles/1.json
  def update
    respond_to do |format|
      if @mobile.update(mobile_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("mobile_row_#{@mobile.id}", partial: 'mobiles/mobile', locals: {mobile: @mobile}) }
        format.html { redirect_to mobile_url(@mobile), notice: "Mobile was successfully updated." }
        format.json { render :show, status: :ok, location: @mobile }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("remote_modal", partial: 'mobiles/form_modal', locals: {mobile: @mobile, partial_file: 'form'}) }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mobiles/1 or /mobiles/1.json
  def destroy
    @mobile.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("mobile_row_#{@mobile.id}") }
      format.html { redirect_to mobiles_url, notice: "Mobile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def count
    @count = Mobile.all.count
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mobile
      @mobile = Mobile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mobile_params
      params.require(:mobile).permit(:brand_name, :ram, :rom, :price)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %> 

  </head>

  <body>
    <div class="container">
      <%= yield %>
      <%= turbo_frame_tag 'remote_modal' %>
    </div>
  </body>
</html>

app/views/mobiles/_form.html.erb
<%= form_with(model: mobile) do |form| %>
  <div class="modal-body" style="background-color: black; color: white;">
    <div style="background-color:yellow">
      <% if mobile.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(mobile.errors.count, "error") %> prohibited this mobile from being saved:</h2>
          <ul>
            <% mobile.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div>
      <%= form.label :brand_name, style: "display: block" %>
      <%= form.text_field :brand_name %>
    </div>

    <div>
      <%= form.label :ram, style: "display: block" %>
      <%= form.text_field :ram %>
    </div>

    <div>
      <%= form.label :rom, style: "display: block" %>
      <%= form.text_field :rom %>
    </div>

    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit 'Submit',class:"btn btn-info", data: { action: "click->bs-modal#submitEnd" } %>
  </div>
<% end %>

app/views/mobiles/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="bs-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel" style="background-color:powderblue;"> <%= params[:action].upcase %>  MOBILE</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div> 
          <%= render partial_file, mobile: mobile %>
      </div>
    </div>
  </div>
<% end %>

app/views/mobiles/_mobile.html.erb
<tr id="mobile_row_<%= mobile.id%>">
  <td><%= mobile.brand_name %></td>
  <td> <%= mobile.ram %></td>
  <td><%= mobile.rom %></td>
  <td><%= mobile.price %></td>
  <td> 
    <%= link_to "Show this mobile", mobile, class:"btn btn-success",data: { controller: "mobile-modal" } %> 

    <%= link_to "Edit this mobile", edit_mobile_path(mobile), class:"btn btn-warning", data: { controller: "mobile-modal" } %> 
    <%= link_to "Destroy", mobile_path(mobile), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: "btn btn-danger" %>                  
  </td>
</tr>

app/views/mobiles/_show_modal.html.erb
 <div class="modal-body" style="background-color: black; color: white; font-size: 20px;" >
   <div class="text-center">
      <td><strong>Brand name :</strong></td>
      <td><%= mobile.brand_name %></td><br>
      <td><strong>Ram :</strong></td>
      <td> <%= mobile.ram %></td><br>
      <td><strong>Rom :</strong></td>
      <td><%= mobile.rom %></td><br>
      <td><strong>Price :</strong></td>
      <td><%= mobile.price %></td>
   </div>
   <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
   </div>
 </div>

app/views/mobiles/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "form_modal", mobile: @mobile, partial_file: 'form' %>
<% end %>

app/views/mobiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>List of Mobiles</h1>
<%= link_to "New mobile", new_mobile_path, data: { controller: 'mobile-modal' }, class:"btn btn-primary" %>

<table class="table table-border"  >
  <thead>
    <tr class="table-primary" >
      <th id='th'>Brand Name</th>
      <th id='th'>Ram</th>
      <th id='th'>Rom</th>
       <th id='th'>Price</th>
      <th colspan="3", style="text-align:center; background-color:black;color:white;font-size:20px;padding-right: 10%;">Action</th>
    </tr>
  </thead>
  <tbody id="mobile_list"  >
      <% @mobiles.each do |mobile| %>
        <%= render 'mobile', mobile: mobile %>
      <% end %>  
  </tbody>
</table>

app/views/mobiles/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "form_modal", mobile: @mobile, partial_file: 'form' %>
<% end %>

app/views/mobiles/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "form_modal", mobile: @mobile, partial_file: 'show_modal' %>
<% end %>